# Basic of Pytorch

## Tensor

Tensor는 array, metrix와 매우 유사한 데이터 구조.
Tensor는 GPU에서 실행할 수 있다는 점을 제외하면 numpy의 ndarray와 유사함.

In [1]:
import torch
import numpy as np

## Initializing a Tensor

### 1. Directly from data

Tensor는 데이터로부터 직접적으로 만들어질 수 있다.

In [2]:
data= [[1,2], [3,4]]
x_data = torch.tensor(data)

In [3]:
print(type(x_data))

<class 'torch.Tensor'>


In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

### 2. From a Numpy array

Tensor는 numpy array로부터 만들어질 수 있다.

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [6]:
print(type(x_np))

<class 'torch.Tensor'>


### 3. From another tensor

새로운 Tensor는 기존의 Tensor의 properties(shape, datatype)를 유지한다.

In [7]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor : \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3513, 0.2636],
        [0.2598, 0.9498]]) 



### 4. With random or constant values

`shape` is a tuple of tensor dimensions.
`shape`는 output tensor의 차원을 결정한다.

In [8]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6844, 0.0933, 0.6379],
        [0.7945, 0.6429, 0.7018]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

Tensor의 Attributes는 shape, datatype, device on which they are stored 보여준다.

In [9]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"DataType of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
DataType of tensor: torch.float32
Device tensor is stored on: cpu


## Operation on Tensors

산술, 선형 대수학, 행렬 조작(transposing, indexing, slicing), sampling 등을 포함한 100개 이상의 tensor 연산이 가능.
(https://pytorch.org/docs/stable/torch.html)

기본적으로 Tensor는 CPU에 생성되며 `.to`를 사용하여 GPU로 이동해야 함.

In [10]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [11]:
torch.cuda.is_available()

True

In [12]:
!nvidia-smi

Fri Jan 19 11:54:06 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080 Ti     On  | 00000000:05:00.0 Off |                  N/A |
| 24%   41C    P2              55W / 250W |    154MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [25]:
# Standard numpy-like indexing and slicing

tensor_ones = torch.ones(4,4)
print(f"First row: {tensor_ones[0]}")
print(f"First column: {tensor_ones[:,0]}")
print(f"Last column : {tensor_ones[:, -1]}")
tensor_ones[:,1] = 0
print(tensor_ones)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column : tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [26]:
# you can use `torch.cat` to concatencate a sequence of tensors
t1 = torch.cat([tensor_ones, tensor_ones, tensor_ones], dim=1) # parameter dim : dimension
print(t1)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


## Bridge with numpy

In [31]:
# Tensor to NumPy array
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [34]:
# Tensor의 변경사항은 Numpy array에도 반영된다.

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")



t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [35]:
# Numpy array to Tensor

n = np.ones(5)
t = torch.from_numpy(n)

In [36]:
#Change in the Numpy array reflects in the tensor

np.add(n, 1, out=n)
print(f"t : {t}")
print(f"n: {n}")

t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
